
addScaleBar Add or remove a scale bar
Description
Uses Leaflet’s built-in scale bar feature to add a scale bar.
### Usage
addScaleBar(map, position = c("topright", "bottomright", "bottomleft",
"topleft"), options = scaleBarOptions())
scaleBarOptions(maxWidth = 100, metric = TRUE, imperial = TRUE,
updateWhenIdle = TRUE)
removeScaleBar(map)
### Arguments
map the map to add the scale bar to
position position of control: "topleft", "topright", "bottomleft", or "bottomright"
options a list of additional options, intended to be provided by a call to scaleBarOptions
maxWidth maximum width of the control in pixels (default 100)
metric if TRUE (the default), show a scale bar in metric units (m/km)
imperial if TRUE (the default), show a scale bar in imperial units (ft/mi)
updateWhenIdle if FALSE (the default), the scale bar is always up-to-date (updated on move). If
TRUE, the control is updated on moveend.
### Examples
leaflet() %>%
addTiles() %>%
addScaleBar()
addSimpleGraticule 21
addSimpleGraticule Add a simple Graticule on the map see https://github.com/
ablakey/Leaflet.SimpleGraticule
Description
Add a simple Graticule on the map see https://github.com/ablakey/Leaflet.SimpleGraticule
### Usage
addSimpleGraticule(map, interval = 20, showOriginLabel = TRUE,
redraw = "move", hidden = FALSE, zoomIntervals = list(),
layerId = NULL, group = NULL)
### Arguments
map a map widget object
interval The spacing in map units between horizontal and vertical lines.
showOriginLabel
true Whether or not to show ’(0,0)’ at the origin.
redraw on which map event to redraw the graticule. On move is default but moveend
can be smoother.
hidden hide on start
zoomIntervals use different intervals in different zoom levels. If not specified, all zoom levels
use value in interval option.
layerId the layer id
group the name of the group this layer belongs to.
### Examples
leaflet() %>%
addTiles() %>%
addSimpleGraticule()
addTerminator Add a daylight layer on top of the map
Description
See https://github.com/joergdietrich/Leaflet.Terminator
22 atlStorms2005
### Usage
addTerminator(map, resolution = 2, time = NULL, layerId = NULL,
group = NULL, options = pathOptions(pointerEvents = "none", clickable
= FALSE))
### Arguments
map a map widget object
resolution the step size at which the terminator points are computed. The step size is 1
degree/resolution, i.e. higher resolution values have smaller step sizes and more
points in the polygon. The default value is 2.
time Time
layerId the layer id
group the name of the group this layer belongs to.
options the path options for the daynight layer
### Examples
leaf <- leaflet() %>%
addTiles() %>%
addTerminator()
leaf
