
easyButtonState Create an easyButton statestate
Description
Create an easyButton statestate
Creates an easy button.
Add a EasyButton on the map see https://github.com/CliffCloud/Leaflet.EasyButton
Add a easyButton bar on the map see https://github.com/CliffCloud/Leaflet.EasyButton
30 easyButtonState
### Usage
easyButtonState(stateName, icon, title, onClick)
easyButton(icon = NULL, title = NULL, onClick = NULL,
position = "topleft", id = NULL, states = NULL)
addEasyButton(map, button)
addEasyButtonBar(map, ..., position = "topleft", id = NULL)
### Arguments
stateName a unique name for the state
icon the button icon
title text to show on hover
onClick the action to take
position topleft|topright|bottomleft|bottomright
id id for the button
states the states
map a map widget object
button the button object created with easyButton
... a list of buttons created with easyButton
Functions
• easyButtonState: state of an easyButton.
• addEasyButton: add an EasyButton to the map
• addEasyButtonBar: add an EasyButton to the map
See Also
easyButton
https://github.com/CliffCloud/Leaflet.EasyButton
addEasyButton
### Examples
leaf <- leaflet() %>%
addTiles() %>%
addEasyButton(easyButton(
icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
onClick = JS("function(btn, map){ map.setZoom(1);}")))
leaf
leaf <- leaflet() %>%
evalFormula 31
addTiles() %>%
addEasyButtonBar(
easyButton(
icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
onClick = JS("function(btn, map){ alert(\"Button 1\");}")),
easyButton(
icon = htmltools::span(class = "star", htmltools::HTML("&target;")),
onClick = JS("function(btn, map){ alert(\"Button 2\");}")))
leaf
evalFormula Evaluate list members that are formulae, using the map data as the
environment (if provided, otherwise the formula environment)
Description
Evaluate list members that are formulae, using the map data as the environment (if provided, otherwise
the formula environment)
### Usage
evalFormula(list, data)
### Arguments
list with members as formulae
data map data
expandLimits Notifies the map of new latitude/longitude of items of interest on the
map
Description
Notifies the map of new latitude/longitude of items of interest on the map
### Usage
expandLimits(map, lat, lng)
### Arguments
map map object
lat vector of latitudes
lng vector of longitudes
32 filterNULL
expandLimitsBbox Same as expandLimits, but takes a polygon (that presumably has a
bbox attr) rather than lat/lng.
Description
Same as expandLimits, but takes a polygon (that presumably has a bbox attr) rather than lat/lng.
### Usage
expandLimitsBbox(map, poly)
### Arguments
map map object
poly A spatial object representing a polygon.



groupOptions Set options on layer groups
Description
Change options on layer groups. Currently the only option is to control what zoom levels a layer
group will be displayed at. The zoomLevels option is not compatible with layers control; do not
both assign a group to zoom levels and use it with addLayersControl.
### Usage
groupOptions(map, group, zoomLevels = NULL)
### Arguments
map the map to modify
group character vector of one or more group names to set options on
zoomLevels numeric vector of zoom levels at which group(s) should be visible, or TRUE to
display at all zoom levels
### Examples
pal <- colorQuantile("YlOrRd", quakes$mag)
leaflet() %>%
# Basic markers
addTiles(group = "basic") %>%
addMarkers(data = quakes, group = "basic") %>%
# When zoomed in, we'll show circles at the base of each marker whose
# radius and color reflect the magnitude
addProviderTiles(providers$Stamen.TonerLite, group = "detail") %>%
addCircleMarkers(data = quakes, group = "detail", fillOpacity = 0.5,
radius = ~mag * 5, color = ~pal(mag), stroke = FALSE) %>%
# Set the detail group to only appear when zoomed in
groupOptions("detail", zoomLevels = 7:18)
iconList Make icon set
Description
Make icon set
### Usage
iconList(...)
icons 35
### Arguments
... icons created from makeIcon()
### Examples
iconSet <- iconList(
red = makeIcon("leaf-red.png", iconWidth = 32, iconHeight = 32),
green = makeIcon("leaf-green.png", iconWidth = 32, iconHeight = 32)
)
iconSet[c("red", "green", "red")]
