
createLeafletMap Legacy functions
Description
These functions are provided for backwards compatibility with the first iteration of the leaflet bindings
(https://github.com/jcheng5/leaflet-shiny).
### Usage
createLeafletMap(session, outputId)
leafletMap(outputId, width, height,
initialTileLayer = "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
initialTileLayerAttribution = NULL, options = NULL)
### Arguments
session, outputId
Deprecated
width, height, initialTileLayer, initialTileLayerAttribution, options
Deprecated
derivePoints Given a data object and lng/lat ### Arguments (which may be NULL
[meaning infer from data], formula [which should be evaluated with
respect to the data], or vector data [which should be used as-is]) return
a lng/lat data frame.
Description
Given a data object and lng/lat ### Arguments (which may be NULL [meaning infer from data], formula
[which should be evaluated with respect to the data], or vector data [which should be used as-is])
return a lng/lat data frame.
28 derivePolygons
### Usage
derivePoints(data, lng = NULL, lat = NULL, missingLng = missing(lng),
missingLat = missing(lat), funcName = "f")
### Arguments
data map data
lng longitude
lat latitude
missingLng whether lng is missing
missingLat whether lat is missing
funcName Name of calling function (for logging)
derivePolygons Given a data object and lng/lat ### Arguments (which may be NULL
[meaning infer from data], formula [which should be evaluated with
respect to the data], or vector data [which should be used as-is]) return
a spatial object
Description
Given a data object and lng/lat ### Arguments (which may be NULL [meaning infer from data], formula
[which should be evaluated with respect to the data], or vector data [which should be used as-is])
return a spatial object
### Usage
derivePolygons(data, lng = NULL, lat = NULL,
missingLng = missing(lng), missingLat = missing(lat),
funcName = "f")
### Arguments
data map data
lng longitude
lat latitude
missingLng whether lng is missing
missingLat whether lat is missing
funcName Name of calling function (for logging)
